site_name: Technotes
site_url: https://marconetto.github.io/technotes
repo_url: https://github.com/marconetto/technotes
extra:
  generator: false
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
theme:
  name: material
  icon:
    logo: material/atom
  features:
    - navigation.sections
    - navigation.expand # keeps all sections expanded
    - navigation.indexes # (optional) use index.md as section landing page
    - navigation.override
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: indigo
      accent: indigo
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: indigo
      accent: indigo
